apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: miguel-kustom-pipeline-run-
spec:
  serviceAccountName: build-bot
  params:
    - name: source-repo
      value: https://github.com/hidsan/kustomize-assignment-app.git
    - name: image-repo
      value: quay.io/miguel_hidalgo_ibm/express-sample-app
    - name: app-name
      value: express-sample-app
  pipelineRef:
    name: kustom-pipeline
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
