apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: vcs-trigger
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: miguel-pipeline-run-
      spec:
        pipelineRef:
          name: kustom-pipeline
        serviceAccountName: build-bot
        params:
          - name: app-name
            value: express-sample-app
          - name: source-repo
            value: https://github.com/hidsan/kustomize-assignment-app.git
          - name: image-repo
            value: quay.io/miguel_hidalgo_ibm/express-sample-app
        workspaces:
          - name: pipeline-shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi